# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jusrnyj5oJKWs5kvsM02uR8inKX6TNnB
"""

import subprocess
subprocess.check_call(['pip', 'install', 'xgboost', 'tensorflow', '--quiet'])

import os, time, json, warnings
warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
import pandas as pd
import requests
from datetime import datetime, timedelta
from pathlib import Path

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import roc_auc_score, f1_score, classification_report

import xgboost as xgb
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

print(f"TensorFlow : {tf.__version__}")
print(f"XGBoost    : {xgb.__version__}")
print("Imports done.")

import shutil
import pathlib
from pathlib import Path

TRAIN_START     = "2005-01-01"
TRAIN_END       = "2022-12-31"
VAL_START       = "2023-01-01"
VAL_END         = "2023-12-31"
SEQUENCE_LENGTH = 30
GRID_ROWS       = 24
GRID_COLS       = 24
N_CHANNELS      = 7          # added slope channel vs v1
CACHE_DIR       = Path("osm_cache")
WEATHER_CACHE_DIR = CACHE_DIR / "weather"   # ← NEW: dedicated folder
CACHE_DIR.mkdir(exist_ok=True)
WEATHER_CACHE_DIR.mkdir(exist_ok=True)
#CACHE_DIR.mkdir(exist_ok=True)

print(f"Grid: {GRID_ROWS} × {GRID_COLS}  (both divisible by 4: OK)")

#shutil.rmtree("osm_cache/weather", ignore_errors=True)
#pathlib.Path("osm_cache/weather").mkdir(exist_ok=True)

# Bangladesh bounding box [south, west, north, east]
BD_BBOX = (20.5, 87.9, 26.7, 92.7)

# Upstream catchments — these cannot come from OSM Bangladesh bbox
# because they are physically outside Bangladesh.
# WHY THEY MATTER: Brahmaputra rain in Assam takes 2-5 days to arrive.
UPSTREAM_FIXED = {
    'Assam_Dhubri':       {'lat': 26.022, 'lon': 89.975},
    'Meghalaya_Shillong': {'lat': 25.578, 'lon': 91.893},
    'Nepal_Birganj':      {'lat': 27.014, 'lon': 84.877},
}

# API endpoints
NASA_POWER_URL  = "https://power.larc.nasa.gov/api/temporal/daily/point"
OVERPASS_URL    = "https://overpass-api.de/api/interpreter"
TOPO_URL        = "https://api.opentopodata.org/v1/srtm30m"
METEO_ARCHIVE   = "https://archive-api.open-meteo.com/v1/archive"
METEO_FORECAST  = "https://api.open-meteo.com/v1/forecast"
NOMINATIM_URL   = "https://nominatim.openstreetmap.org/search"

def fetch_osm_rivers(bbox=BD_BBOX, cache_file=CACHE_DIR / "osm_rivers.json"):
    """
    Queries OSM Overpass for all named rivers inside Bangladesh.
    Returns a list of {name, lat, lon} dicts.
    Uses disk cache — first call takes ~60s, subsequent calls instant.
    """
    if cache_file.exists():
        print("  Loading OSM rivers from cache ...")
        return json.loads(cache_file.read_text())

    print("  Querying OSM Overpass API for Bangladesh rivers ...")
    south, west, north, east = bbox

    # Overpass QL query:
    # Find all 'way' and 'node' elements tagged as waterway=river
    # inside the Bangladesh bounding box, then output their coords.
    query = f"""
    [out:json][timeout:60];
    (
      way["waterway"~"river|stream"]["name"]
         ({south},{west},{north},{east});
    );
    out center tags;
    """
    try:
        r = requests.post(OVERPASS_URL, data={'data': query}, timeout=90)
        r.raise_for_status()
        data = r.json()
    except Exception as e:
        print(f"  Overpass failed: {e}. Using fallback stations.")
        return _fallback_stations()

    rivers = {}
    for el in data.get('elements', []):
        name = el.get('tags', {}).get('name', 'Unknown')
        center = el.get('center', {})
        if center.get('lat') and center.get('lon'):
            if name not in rivers:
                rivers[name] = []
            rivers[name].append({'lat': center['lat'], 'lon': center['lon']})

    # Sample one point per ~0.3° along each major river
    stations = []
    for river_name, points in rivers.items():
        pts = sorted(points, key=lambda p: p['lat'])
        sampled, last_lat = [], -99
        for p in pts:
            if p['lat'] - last_lat > 0.28:
                sampled.append({'name': river_name, 'lat': p['lat'], 'lon': p['lon']})
                last_lat = p['lat']
        stations.extend(sampled[:8])   # cap per river to avoid too many API calls

    print(f"  Discovered {len(stations)} monitoring points across {len(rivers)} rivers.")
    cache_file.write_text(json.dumps(stations))
    return stations


def fetch_elevations(stations, cache_file=CACHE_DIR / "elevations.json"):
    """
    Calls OpenTopoData SRTM-30m API to get real ground elevation
    for every monitoring point.

    API: https://api.opentopodata.org/v1/srtm30m?locations=lat,lon|lat,lon
    Free: YES — no key, 100 points per request, 1 request/second

    WHY ELEVATION IS CRITICAL FOR PROBLEM 1+2:
    A place at 2m elevation near a river will flood with 50mm of
    rain. The same rainfall at 40m elevation will not flood.
    This is the physics knowledge that generalises to areas with
    no flood history.
    """
    if cache_file.exists():
        print("  Loading elevations from cache ...")
        elev_map = json.loads(cache_file.read_text())
        for st in stations:
            key = f"{st['lat']:.4f},{st['lon']:.4f}"
            st['elevation_m'] = elev_map.get(key, 10.0)
        return stations

    print("  Fetching SRTM elevations from OpenTopoData ...")
    elev_map = {}
    batch_size = 80   # API allows 100; use 80 to stay safe

    for i in range(0, len(stations), batch_size):
        batch = stations[i:i + batch_size]
        locs  = "|".join(f"{s['lat']:.4f},{s['lon']:.4f}" for s in batch)
        try:
            r = requests.get(TOPO_URL, params={'locations': locs}, timeout=30)
            r.raise_for_status()
            results = r.json().get('results', [])
            for st, res in zip(batch, results):
                key = f"{st['lat']:.4f},{st['lon']:.4f}"
                elev_map[key] = res.get('elevation', 10.0)
        except Exception as e:
            print(f"  Elevation batch failed: {e}")
            for st in batch:
                key = f"{st['lat']:.4f},{st['lon']:.4f}"
                elev_map[key] = 10.0
        time.sleep(1.1)   # respect 1 req/s rate limit

    for st in stations:
        key = f"{st['lat']:.4f},{st['lon']:.4f}"
        st['elevation_m'] = elev_map.get(key, 10.0)

    cache_file.write_text(json.dumps(elev_map))
    return stations


def compute_slope(stations):
    """
    Estimates terrain slope for each monitoring point by comparing
    its elevation to its nearest neighbours.

    WHY SLOPE MATTERS FOR PROBLEM 1+2:
    Flat land (slope ~0°) traps water. Steep land (slope >5°) drains
    it. A never-flooded area on a flat river delta with 1m elevation
    is at extreme risk even without any historical flood record.
    """
    if len(stations) < 3:
        for s in stations:
            s['slope'] = 0.5
        return stations

    lats = np.array([s['lat'] for s in stations])
    lons = np.array([s['lon'] for s in stations])
    elevs = np.array([s['elevation_m'] for s in stations])

    for i, s in enumerate(stations):
        # Find 4 nearest neighbours
        dists = np.sqrt((lats - s['lat'])**2 + (lons - s['lon'])**2)
        dists[i] = 999
        nn_idx = np.argsort(dists)[:4]
        if len(nn_idx) == 0:
            s['slope'] = 0.5
            continue
        elev_diffs = np.abs(elevs[nn_idx] - s['elevation_m'])
        dist_deg   = dists[nn_idx]
        dist_m     = dist_deg * 111_000   # approx metres per degree
        slopes     = elev_diffs / (dist_m + 1)
        s['slope'] = float(np.mean(slopes))

    return stations


def _fallback_stations():
    """
    Used if Overpass API is down. Returns the same 12 districts
    as version 1 but WITHOUT static risk_zone — just lat/lon.
    """
    return [
        {'name': 'Brahmaputra', 'lat': 25.807, 'lon': 89.636},
        {'name': 'Brahmaputra', 'lat': 25.328, 'lon': 89.528},
        {'name': 'Jamuna',      'lat': 24.937, 'lon': 89.937},
        {'name': 'Jamuna',      'lat': 24.451, 'lon': 89.701},
        {'name': 'Jamuna',      'lat': 24.251, 'lon': 89.917},
        {'name': 'Surma',       'lat': 25.069, 'lon': 91.399},
        {'name': 'Surma',       'lat': 24.899, 'lon': 91.872},
        {'name': 'Kongsha',     'lat': 24.870, 'lon': 90.727},
        {'name': 'Padma',       'lat': 23.864, 'lon': 90.000},
        {'name': 'Padma',       'lat': 24.363, 'lon': 88.601},
        {'name': 'Buriganga',   'lat': 23.724, 'lon': 90.408},
        {'name': 'Meghna',      'lat': 23.200, 'lon': 90.700},
    ]

import numpy as np
import pandas as pd


def compute_physics_features(df, elevation_m, slope, river_name="",
                              seasonal_rain_mean=None):
    """
    Converts raw weather data into physics-based flood features.

    New in this version:
      - Removed hard seasonal binary flags (is_monsoon etc.)
      - Added percentile-rank features that are month-agnostic
      - climate_shock_idx fires on extreme physical conditions
        regardless of calendar month
    """
    df = df.copy().sort_index()

    # ── Elevation physics ──────────────────────────────────────
    df['elevation_m']    = elevation_m
    df['low_elev_score'] = 1.0 / (1.0 + elevation_m / 15.0)

    # ── Slope ──────────────────────────────────────────────────
    df['slope']          = slope
    df['flat_land_score']= 1.0 / (1.0 + slope * 5000)

    # ── Flood Susceptibility Index (FSI) ──────────────────────
    # Pure physics — works for any location, any season
    df['flood_susceptibility_idx'] = (df['low_elev_score']
                                      * df['flat_land_score'])

    # ── Soil moisture ──────────────────────────────────────────
    if 'soil_moisture' not in df.columns:
        df['soil_moisture'] = 0.5
    df['soil_moisture'] = (df['soil_moisture']
                           .fillna(method='ffill').fillna(0.5))

    # ── Antecedent Precipitation Index ────────────────────────
    weights   = np.array([0.5**i for i in range(30)])
    rain_vals = df['rainfall_mm'].fillna(0).values
    api_vals  = np.zeros(len(df))
    for i in range(1, len(df)):
        window      = rain_vals[max(0, i-30):i][::-1]
        w           = weights[:len(window)]
        api_vals[i] = np.dot(window, w)
    df['antecedent_precip_idx'] = api_vals

    # ── Saturation index ──────────────────────────────────────
    rain_14d = df['rainfall_mm'].fillna(0).rolling(14).sum()
    df['saturation_idx'] = (
        df['soil_moisture'] * 0.6
        + (rain_14d / (rain_14d.max() + 1)) * 0.4
    ).clip(0, 1).fillna(0)

    # ── Rainfall anomaly ──────────────────────────────────────
    # today ÷ monthly mean — still useful but now supplemented
    # by month-agnostic percentile features
    if seasonal_rain_mean is not None and seasonal_rain_mean > 0:
        df['rain_anomaly'] = df['rainfall_mm'] / seasonal_rain_mean
    else:
        monthly_mean       = df['rainfall_mm'].groupby(
            df.index.month).transform('mean')
        df['rain_anomaly'] = df['rainfall_mm'] / (monthly_mean + 1)
    df['rain_anomaly'] = df['rain_anomaly'].fillna(1.0).clip(0, 20)

    # ── Rolling windows ───────────────────────────────────────
    for w in [3, 5, 7, 14, 30]:
        df[f'rain_{w}d_sum']  = df['rainfall_mm'].rolling(w).sum()
        df[f'rain_{w}d_max']  = df['rainfall_mm'].rolling(w).max()
        df[f'rain_{w}d_mean'] = df['rainfall_mm'].rolling(w).mean()

    # ── Lag features ──────────────────────────────────────────
    for lag in [1, 2, 3, 5, 7, 10, 14]:
        df[f'rain_lag{lag}d'] = df['rainfall_mm'].shift(lag)
        df[f'wl_lag{lag}d']   = df['water_level_m'].shift(lag)

    # ── Water level derived ───────────────────────────────────
    df['wl_7d_mean']   = df['water_level_m'].rolling(7).mean()
    df['wl_7d_std']    = df['water_level_m'].rolling(7).std().fillna(0)
    df['wl_trend_7d']  = df['water_level_m'] - df['water_level_m'].shift(7)
    df['wl_change_1d'] = df['water_level_m'].diff(1)
    df['wl_change_3d'] = df['water_level_m'].diff(3)
    df['wl_3d_max']    = df['water_level_m'].rolling(3).max()

    # ── Soft seasonal encoding (continuous, kept) ─────────────
    # month_sin/cos are continuous — they give the model a
    # smooth seasonal signal without hard blocking.
    # doy_sin/cos give finer within-year resolution.
    df['month']    = df.index.month
    df['doy']      = df.index.dayofyear
    df['month_sin']= np.sin(2 * np.pi * df['month'] / 12)
    df['month_cos']= np.cos(2 * np.pi * df['month'] / 12)
    df['doy_sin']  = np.sin(2 * np.pi * df['doy'] / 365)
    df['doy_cos']  = np.cos(2 * np.pi * df['doy'] / 365)

    # REMOVED: is_monsoon, is_premonsoon, is_postmonsoon
    # These hard binary flags blocked the model from responding
    # to early-monsoon or out-of-season extreme events.

    # ── Days from monsoon peak (continuous, not binary) ───────
    # Historical monsoon peak ≈ August 1 = doy 213.
    # This gives the model a smooth "how far from peak monsoon"
    # signal. It is large in winter, small in summer.
    # Critically: it is CONTINUOUS — an early June event
    # (doy 152) sits at distance 61 from peak, while August
    # (doy 213) sits at distance 0. The model can learn
    # "even at distance 61, FSI=0.9 means danger" without a
    # hard gate blocking it.
    doy_vals = df['doy'].values.astype(float)
    raw_dist = np.abs(doy_vals - 213)
    df['days_from_monsoon_peak'] = np.minimum(raw_dist,
                                               365 - raw_dist)

    # ── Temperature range ─────────────────────────────────────
    df['temp_range'] = (df.get('temp_max', pd.Series(30, index=df.index))
                        - df.get('temp_min', pd.Series(20, index=df.index)))

    # ── CLIMATE-AGNOSTIC PERCENTILE FEATURES ──────────────────
    # These three features are the core of the seasonal-blocking
    # fix. They compare each day against the ENTIRE historical
    # distribution — not against other days in the same month.

    # pct_rain_7d
    # Where does today's 7-day rain total rank among ALL days?
    # 0.95 = top 5% of all days ever — regardless of month.
    # An extreme May rainfall event ranks identically to an
    # equivalent August event.
    rain7 = df['rain_7d_sum'].fillna(0)
    df['pct_rain_7d'] = rain7.rank(pct=True, method='average')

    # pct_api
    # Where does today's soil saturation (API) rank overall?
    api_s = pd.Series(api_vals, index=df.index)
    df['pct_api'] = api_s.rank(pct=True, method='average')

    # pct_water_level
    # Where does today's river level rank overall?
    df['pct_water_level'] = (df['water_level_m']
                             .rank(pct=True, method='average'))

    # climate_shock_idx
    # Composite month-agnostic danger signal.
    # Weights:
    #   0.35 × rainfall intensity (7-day rank)
    #   0.35 × river level (rank)
    #   0.20 × soil saturation (API rank)
    #   0.10 × FSI (physical vulnerability — static per location)
    # A value near 1.0 means all indicators are simultaneously
    # at historical extremes — the model MUST flag this as
    # dangerous regardless of the calendar month.
    df['climate_shock_idx'] = (
        0.35 * df['pct_rain_7d']
      + 0.35 * df['pct_water_level']
      + 0.20 * df['pct_api']
      + 0.10 * df['flood_susceptibility_idx'].clip(0, 1)
    )

    # ── Final cleanup ─────────────────────────────────────────
    df = df.dropna(subset=['rainfall_mm', 'water_level_m'])
    df = df.fillna(method='ffill').fillna(0)
    return df

def compute_dynamic_risk_score(df_today, df_history):
    """
    Computes a 0-1 flood risk score from current conditions
    compared to seasonal norms. No static labels.

    Parameters:
        df_today   : single-row DataFrame for the date being assessed
        df_history : full historical DataFrame for the same station
                     (used to compute seasonal percentiles)
    Returns:
        float in [0, 1]
    """
    today_month = df_today.index[0].month

    # Seasonal subset for percentile calculation
    same_month_hist = df_history[df_history.index.month == today_month]
    if len(same_month_hist) < 10:
        same_month_hist = df_history   # fall back to full history if too few

    def safe_pct(series, pct):
        v = series.dropna()
        return float(np.percentile(v, pct)) if len(v) > 0 else 1.0

    wl_median  = safe_pct(same_month_hist['water_level_m'], 50)
    rain7_p90  = safe_pct(same_month_hist.get('rain_7d_sum',
                   same_month_hist['rainfall_mm'].rolling(7).sum()), 90)
    api_p90    = safe_pct(same_month_hist.get('antecedent_precip_idx',
                   pd.Series([1])), 90)

    # Component 1: Water level anomaly
    wl_now  = float(df_today['water_level_m'].iloc[0])
    c1      = np.clip(wl_now / (wl_median + 0.01) - 0.5, 0, 3) / 3.0

    # Component 2: Rainfall intensity
    rain7_now = float(df_today.get('rain_7d_sum', df_today['rainfall_mm']).iloc[0])
    c2        = np.clip(rain7_now / (rain7_p90 + 0.01), 0, 2) / 2.0

    # Component 3: Soil/catchment saturation
    api_now = float(df_today.get('antecedent_precip_idx', pd.Series([0])).iloc[0])
    c3      = np.clip(api_now / (api_p90 + 0.01), 0, 1)

    # Component 4: Upstream pressure (using available upstream lag features)
    upstream_cols = [c for c in df_today.columns if c.startswith('up_')]
    if upstream_cols:
        up_vals = df_today[upstream_cols].iloc[0].values
        c4      = np.clip(float(up_vals.mean()) / 50.0, 0, 1)
    else:
        c4 = c2 * 0.5   # proxy from local rain if no upstream data

    score = 0.40 * c1 + 0.30 * c2 + 0.20 * c3 + 0.10 * c4
    return float(np.clip(score, 0, 1))


def risk_level_from_score(score):
    """Converts 0-1 score to human-readable level and colour code."""
    if score < 0.20:   return "SAFE",    "\033[92m",  "green"
    if score < 0.45:   return "WATCH",   "\033[93m",  "yellow"
    if score < 0.68:   return "WARNING", "\033[33m",  "orange"
    if score < 0.85:   return "DANGER",  "\033[91m",  "red"
    return                    "EXTREME", "\033[41m",  "darkred"

def fetch_weather(lat, lon, start_date, end_date, name=""):
    """Calls Open-Meteo Archive."""

    try:
        # --- Fetch daily data ---
        daily_params = {
            'latitude': lat, 'longitude': lon,
            'start_date': start_date, 'end_date': end_date,
            'daily': ['precipitation_sum', 'temperature_2m_max',
                      'temperature_2m_min', 'wind_speed_10m_max',
                      'relative_humidity_2m'],
            'timezone': 'Asia/Dhaka',
        }
        r_daily = requests.get(METEO_ARCHIVE, params=daily_params, timeout=45)
        r_daily.raise_for_status()
        daily_data = r_daily.json()['daily']

        df = pd.DataFrame({
            'date':             pd.to_datetime(daily_data['time']),
            'rainfall_mm':      daily_data['precipitation_sum'],
            'temp_max':         daily_data['temperature_2m_max'],
            'temp_min':         daily_data['temperature_2m_min'],
            'wind_speed':       daily_data['wind_speed_10m_max'],
            'evapotranspiration': np.nan, # Removed from API call, set to NaN
            'humidity':         daily_data['relative_humidity_2m'],
        })
        df['station'] = name
        df = df.set_index('date')

        # --- Fetch hourly soil moisture ---
        hourly_params = {
            'latitude': lat, 'longitude': lon,
            'start_date': start_date, 'end_date': end_date,
            'hourly': 'soil_moisture_0_to_7cm',
            'timezone': 'Asia/Dhaka',
        }
        r_hourly = requests.get(METEO_ARCHIVE, params=hourly_params, timeout=45)
        r_hourly.raise_for_status()
        hourly_data = r_hourly.json()['hourly']

        h = pd.DataFrame({'dt': pd.to_datetime(hourly_data['time']),
                           'sm': hourly_data['soil_moisture_0_to_7cm']})
        h['date'] = h['dt'].dt.normalize()
        hourly_mean_sm = h.groupby('date')['sm'].mean().rename('soil_moisture')
        df = df.merge(hourly_mean_sm, on='date', how='left')

        return df

    except Exception as e:
        print(f"  [WEATHER WARN] {name}: {e}")
        return None

# ================================================================
# VERIFIED BANGLADESH STATION LIST  (replaces OSM)
#
# Source: BWDB Hydrological Year Book 2020 + FFWC station index
#         + Google Maps coordinate verification
# All stations confirmed inside Bangladesh, on flood-prone rivers,
# elevation < 50m (genuine floodplain locations).
# ================================================================

# ── NASA POWER parameter mapping ─────────────────────────────────
#
#  NASA name        → our column name
#  PRECTOTCORR      → rainfall_mm       (bias-corrected precipitation, mm/day)
#  T2M_MAX          → temp_max          (max air temp at 2m, °C)
#  T2M_MIN          → temp_min          (min air temp at 2m, °C)
#  WS2M             → wind_speed        (wind speed at 2m, m/s)
#  RH2M             → humidity          (relative humidity at 2m, %)
#  GWETROOT         → soil_moisture     (root zone soil wetness, 0–1)
#  EVPTRNS          → evapotranspiration (evapotranspiration, mm/day)
#
NASA_PARAMS = "PRECTOTCORR,T2M_MAX,T2M_MIN,WS2M,RH2M,GWETROOT,EVPTRNS"

BANGLADESH_STATIONS = [
    # Brahmaputra / Jamuna corridor
    {'name': 'Brahmaputra', 'district': 'Kurigram',
     'lat': 25.807, 'lon': 89.636, 'elev_hint': 12},
    {'name': 'Brahmaputra', 'district': 'Gaibandha',
     'lat': 25.328, 'lon': 89.528, 'elev_hint': 18},
    {'name': 'Jamuna',      'district': 'Jamalpur',
     'lat': 24.937, 'lon': 89.937, 'elev_hint': 15},
    {'name': 'Jamuna',      'district': 'Sirajganj',
     'lat': 24.451, 'lon': 89.701, 'elev_hint':  9},
    {'name': 'Jamuna',      'district': 'Tangail',
     'lat': 24.251, 'lon': 89.917, 'elev_hint': 11},
    {'name': 'Jamuna',      'district': 'Bogura',
     'lat': 24.851, 'lon': 89.370, 'elev_hint': 20},
    {'name': 'Teesta',      'district': 'Lalmonirhat',
     'lat': 25.919, 'lon': 89.449, 'elev_hint': 32},
    {'name': 'Atrai',       'district': 'Naogaon',
     'lat': 24.920, 'lon': 88.930, 'elev_hint': 22},
    # Padma / Ganges
    {'name': 'Padma',       'district': 'Rajshahi',
     'lat': 24.363, 'lon': 88.601, 'elev_hint': 22},
    {'name': 'Padma',       'district': 'Manikganj',
     'lat': 23.864, 'lon': 90.000, 'elev_hint':  8},
    {'name': 'Padma',       'district': 'Faridpur',
     'lat': 23.607, 'lon': 89.843, 'elev_hint':  6},
    {'name': 'Kumar',       'district': 'Magura',
     'lat': 23.490, 'lon': 89.419, 'elev_hint':  7},
    # Meghna
    {'name': 'Meghna',      'district': 'Bhairab Bazar',
     'lat': 24.052, 'lon': 90.978, 'elev_hint':  6},
    {'name': 'Meghna',      'district': 'Chandpur',
     'lat': 23.232, 'lon': 90.657, 'elev_hint':  4},
    {'name': 'OldBrahmaputra', 'district': 'Mymensingh',
     'lat': 24.746, 'lon': 90.407, 'elev_hint': 18},
    # Surma-Meghna / Haor basin
    {'name': 'Surma',       'district': 'Sunamganj',
     'lat': 25.069, 'lon': 91.399, 'elev_hint':  3},
    {'name': 'Surma',       'district': 'Sylhet',
     'lat': 24.899, 'lon': 91.872, 'elev_hint': 30},
    {'name': 'Kongsha',     'district': 'Netrokona',
     'lat': 24.870, 'lon': 90.727, 'elev_hint': 20},
    {'name': 'Kushiyara',   'district': 'Habiganj',
     'lat': 24.374, 'lon': 91.415, 'elev_hint':  9},
    # Buriganga / Dhaka urban
    {'name': 'Buriganga',   'district': 'Dhaka',
     'lat': 23.724, 'lon': 90.408, 'elev_hint':  8},
    {'name': 'Turag',       'district': 'Gazipur',
     'lat': 23.990, 'lon': 90.369, 'elev_hint':  9},
    # Southern delta / coastal
    {'name': 'Pasur',       'district': 'Khulna',
     'lat': 22.833, 'lon': 89.533, 'elev_hint':  2},
    {'name': 'Kirtankhola', 'district': 'Barishal',
     'lat': 22.701, 'lon': 90.370, 'elev_hint':  3},
    {'name': 'Feni',        'district': 'Feni',
     'lat': 22.916, 'lon': 91.396, 'elev_hint':  7},
    {'name': 'Karnaphuli',  'district': 'Chattogram',
     'lat': 22.341, 'lon': 91.830, 'elev_hint': 10},
]

print(f"Station list: {len(BANGLADESH_STATIONS)} verified stations")
print(f"Rivers: {len(set(s['name'] for s in BANGLADESH_STATIONS))} unique")
print(f"Districts: {len(set(s['district'] for s in BANGLADESH_STATIONS))} unique")

# NEW — DISK CACHE HELPERS  (three small functions)
# ================================================================

def _cache_csv(label):
    """Returns the CSV path for a station."""
    safe = label.replace(' ', '_').replace('/', '_')
    return WEATHER_CACHE_DIR / f"{safe}.csv"

def _cache_meta(label):
    safe = label.replace(' ', '_').replace('/', '_')
    return WEATHER_CACHE_DIR / f"{safe}_meta.json"

def save_to_cache(label, df, elevation_m):
    df.to_csv(_cache_csv(label))
    _cache_meta(label).write_text(
        json.dumps({'elevation_m': elevation_m}))

def load_from_cache(label):
    """
    Returns (df, elevation_m) if a cache file exists, else (None, None).
    The station is completely skipped from the API if cached.
    """
    #csv_path  = _cache_csv(label)
    #meta_path = WEATHER_CACHE_DIR / f"{label.replace(' ','_').replace('/','_')}_meta.json"
    #if not csv_path.exists() or not meta_path.exists():
        #return None, None
    if not _cache_csv(label).exists() or not _cache_meta(label).exists():
        return None, None
    #df   = pd.read_csv(csv_path, index_col='date', parse_dates=True)
    #meta = json.loads(meta_path.read_text())
    #return df, float(meta.get('elevation_m', 10.0))
    df   = pd.read_csv(_cache_csv(label),
                       index_col='date', parse_dates=True)
    meta = json.loads(_cache_meta(label).read_text())
    return df, float(meta.get('elevation_m', 10.0))


def _date_to_nasa(date_str):
    """Converts '2015-01-01' → '20150101' for NASA POWER API."""
    return date_str.replace('-', '')


def fetch_nasa_power(lat, lon, start_date, end_date,
                     name="", elevation_m=10.0, max_retries=4):
    """
    Fetches daily weather data from NASA POWER API.

    NASA POWER advantages over Open-Meteo for this use case:
      - No hourly quota limit
      - Returns the entire date range in one request
      - No authentication needed
      - Reliable for research use (backed by NASA LaRC)

    Parameters
    ----------
    lat, lon      : station coordinates
    start_date    : "YYYY-MM-DD"
    end_date      : "YYYY-MM-DD"
    name          : label for the station (used in output)
    elevation_m   : passed in from elev_hint (NASA does not return elevation)
    max_retries   : retry attempts on network failure

    Returns
    -------
    (df, elevation_m)  on success — elevation is the passed-in value
    (None, 10.0)       on failure
    """
    # Check disk cache first — no API call if already fetched
    cached_df, cached_elev = load_from_cache(name)
    if cached_df is not None:
        return cached_df, cached_elev

    params = {
        "parameters": NASA_PARAMS,
        "community":  "AG",          # Agroclimatology — best for hydrology
        "longitude":  lon,
        "latitude":   lat,
        "start":      _date_to_nasa(start_date),
        "end":        _date_to_nasa(end_date),
        "format":     "JSON",
    }

    for attempt in range(1, max_retries + 1):
        try:
            r = requests.get(NASA_POWER_URL, params=params, timeout=120)

            # NASA returns 429 very rarely but handle it anyway
            if r.status_code == 429:
                wait = 30 * attempt
                print(f"  [429] NASA rate limit — waiting {wait}s ...")
                time.sleep(wait)
                continue

            # NASA sometimes returns 5xx on server load
            if r.status_code >= 500:
                wait = 20 * attempt
                print(f"  [{r.status_code}] NASA server busy — "
                      f"waiting {wait}s (attempt {attempt}) ...")
                time.sleep(wait)
                continue

            r.raise_for_status()
            data   = r.json()
            params_data = data['properties']['parameter']

            # Build date index from PRECTOTCORR keys (YYYYMMDD strings)
            date_keys = list(params_data['PRECTOTCORR'].keys())
            dates     = pd.to_datetime(date_keys, format='%Y%m%d')

            def _extract(key):
                """Gets values for a parameter, replacing -999 with NaN."""
                vals = [params_data[key].get(d, np.nan) for d in date_keys]
                arr  = np.array(vals, dtype=float)
                arr[arr <= -998] = np.nan
                return arr

            df = pd.DataFrame({
                'date':               dates,
                'rainfall_mm':        _extract('PRECTOTCORR'),
                'temp_max':           _extract('T2M_MAX'),
                'temp_min':           _extract('T2M_MIN'),
                'wind_speed':         _extract('WS2M'),
                'humidity':           _extract('RH2M'),
                'soil_moisture':      _extract('GWETROOT'),
                'evapotranspiration': _extract('EVPTRNS'),
            })

            df['station'] = name
            df = df.set_index('date').sort_index()

            # Forward-fill any remaining NaN (isolated missing days)
            df = df.fillna(method='ffill').fillna(method='bfill')

            # Save to disk immediately
            save_to_cache(name, df, elevation_m)
            return df, elevation_m

        except requests.exceptions.Timeout:
            print(f"  [TIMEOUT] {name} — attempt {attempt}/{max_retries} ...")
            time.sleep(15 * attempt)

        except requests.exceptions.ConnectionError as e:
            print(f"  [CONN ERR] {name}: {e}")
            time.sleep(10 * attempt)

        except KeyError as e:
            print(f"  [PARSE ERR] {name}: missing key {e} in NASA response")
            return None, elevation_m

        except Exception as e:
            print(f"  [ERR] {name}: {e}")
            return None, elevation_m

    print(f"  [SKIP] {name}: all {max_retries} retries exhausted.")
    return None, elevation_m


# ================================================================
# FORECAST FETCH  (still uses Open-Meteo — NASA has no forecast)
# ================================================================

def fetch_forecast(lat, lon, name="", days=7):
    """
    Fetches next N-day forecast from Open-Meteo Forecast API.
    This is lightweight (7 days only) and has no quota issue.
    NASA POWER is historical-only so we keep this for predictions.
    """
    params = {
        'latitude':      lat,
        'longitude':     lon,
        'daily': [
            'precipitation_sum',
            'temperature_2m_max',
            'wind_speed_10m_max',
            'precipitation_probability_max',
        ],
        'forecast_days': days,
        'timezone':      'Asia/Dhaka',
    }
    for attempt in range(3):
        try:
            r = requests.get(METEO_FORECAST, params=params, timeout=30)
            if r.status_code == 429:
                time.sleep(10 * (2 ** attempt))
                continue
            r.raise_for_status()
            d  = r.json()['daily']
            n  = len(d['time'])
            df = pd.DataFrame({
                'date':            pd.to_datetime(d['time']),
                'rainfall_mm':     d['precipitation_sum'],
                'temp_max':        d['temperature_2m_max'],
                'wind_speed':      d['wind_speed_10m_max'],
                'rain_probability':d.get(
                    'precipitation_probability_max', [50]*n),
            })
            df['station'] = name
            return df.set_index('date')
        except Exception as e:
            print(f"  [FORECAST WARN] {name}: {e}")
    return None


# ================================================================
# SLOPE + WATER LEVEL  (unchanged)
# ================================================================

def compute_slope(stations):
    if len(stations) < 3:
        for s in stations:
            s.setdefault('slope', 0.0001)
        return stations
    lats  = np.array([s['lat']                   for s in stations])
    lons  = np.array([s['lon']                   for s in stations])
    elevs = np.array([s.get('elevation_m', 10.0) for s in stations])
    for i, s in enumerate(stations):
        dists    = np.sqrt((lats - s['lat'])**2 + (lons - s['lon'])**2)
        dists[i] = 999.0
        nn       = np.argsort(dists)[:4]
        dist_m   = dists[nn] * 111_000 + 1.0
        s['slope'] = float(np.mean(
            np.abs(elevs[nn] - s.get('elevation_m', 10.0)) / dist_m))
    return stations


def simulate_water_level(df, elevation_m):
    """
    Physics-based water level from rainfall + elevation.
    85th-percentile danger threshold guarantees ~15% flood rate.
    """
    np.random.seed(abs(int(elevation_m * 100)) % (2**31 - 1))
    n        = len(df)
    doy      = df.index.dayofyear.values
    seasonal = 2.0 + 1.8 * np.sin(2 * np.pi * (doy - 80) / 365)
    rain     = df['rainfall_mm'].fillna(0).values
    lagged   = np.zeros(n)
    for lag, w in [(2, 0.35), (3, 0.40), (4, 0.15), (5, 0.10)]:
        pad     = np.pad(rain, (lag, 0), mode='constant')[:n]
        lagged += w * pad
    mx = lagged.max()
    if mx > 0:
        lagged = (lagged / mx) * (5.0 / (1.0 + elevation_m / 10.0))
    water_level   = seasonal + lagged + np.random.normal(0, 0.15, n)
    danger_thresh = float(np.percentile(water_level, 85))
    df = df.copy()
    df['water_level_m']  = water_level
    df['danger_thresh']  = danger_thresh
    df['flood_occurred'] = (water_level > danger_thresh).astype(int)
    df['flood_severity'] = np.clip(
        np.digitize(water_level,
                    [0,
                     danger_thresh * 0.60,
                     danger_thresh * 0.85,
                     danger_thresh]) - 1, 0, 3)
    return df


# ================================================================
# MAIN LOAD FUNCTION
# ================================================================

def load_all_data():
    # ── Cache status report ──────────────────────────────────────
    cached_labels = [
        f"{s['name']}_{s['district']}"
        for s in BANGLADESH_STATIONS
        if _cache_csv(f"{s['name']}_{s['district']}").exists()
    ]
    missing_labels = [
        f"{s['name']}_{s['district']}"
        for s in BANGLADESH_STATIONS
        if not _cache_csv(f"{s['name']}_{s['district']}").exists()
    ]

    print("\n" + "=" * 62)
    print(" STEP 1: Station List  (NASA POWER API + disk cache)")
    print("=" * 62)
    print(f"  Total stations      : {len(BANGLADESH_STATIONS)}")
    print(f"  Already cached      : {len(cached_labels)}  → instant load")
    print(f"  Need fetching       : {len(missing_labels)}  → NASA POWER API")
    if missing_labels:
        print(f"  Will fetch: {missing_labels}")

    print("\n" + "=" * 62)
    print(" STEP 2: Upstream Catchment Data  (India / Nepal)")
    print("=" * 62)
    upstream_data = {}

    for name, info in UPSTREAM_FIXED.items():
        cached_df, cached_elev = load_from_cache(name)
        if cached_df is not None:
            upstream_data[name] = cached_df
            print(f"  {name:<26} CACHED  rows={len(cached_df)}")
            continue

        print(f"  Fetching {name} via NASA POWER ...", end=' ', flush=True)
        df, elev = fetch_nasa_power(
            info['lat'], info['lon'],
            TRAIN_START, VAL_END,
            name=name, elevation_m=50)
        if df is not None:
            upstream_data[name] = df
            print(f"OK  rows={len(df)}")
        else:
            print("FAILED")
        time.sleep(2.0)   # polite delay — NASA asks for reasonable pauses

    print("\n" + "=" * 62)
    print(" STEP 3: Bangladesh Station Weather")
    print("=" * 62)

    station_data  = {}
    station_metas = []

    for st in BANGLADESH_STATIONS:
        label      = f"{st['name']}_{st['district']}"
        elev_hint  = st.get('elev_hint', 10)

        # ── Load from cache if available ──────────────────────
        cached_df, cached_elev = load_from_cache(label)
        if cached_df is not None:
            cached_df = simulate_water_level(cached_df, cached_elev)
            info = {**st, 'label': label, 'elevation_m': cached_elev}
            station_data[label]  = (cached_df, info)
            station_metas.append(info)
            flood_pct = cached_df['flood_occurred'].mean() * 100
            print(f"  {label:<36} CACHED  "
                  f"elev={cached_elev:4.0f}m  flood={flood_pct:.1f}%")
            continue

        # ── Fetch from NASA POWER ─────────────────────────────
        print(f"  {label:<36} ...", end=' ', flush=True)
        df, elev = fetch_nasa_power(
            st['lat'], st['lon'],
            TRAIN_START, VAL_END,
            name=label,
            elevation_m=elev_hint,   # NASA doesn't return elevation
        )

        if df is not None:
            st['elevation_m'] = elev_hint
            df   = simulate_water_level(df, elev_hint)
            info = {**st, 'label': label}
            station_data[label]  = (df, info)
            station_metas.append(info)
            flood_pct = df['flood_occurred'].mean() * 100
            print(f"OK  elev={elev_hint:4}m  "
                  f"rows={len(df)}  flood={flood_pct:.1f}%")
        else:
            print("FAILED — re-run to retry")

        time.sleep(2.0)   # 2s between requests is sufficient for NASA

    # Compute slope from elevation values
    station_metas = compute_slope(station_metas)
    for meta in station_metas:
        if meta['label'] in station_data:
            station_data[meta['label']][1]['slope'] = meta['slope']

    # ── Summary ───────────────────────────────────────────────
    overall_flood = (
        np.mean([df['flood_occurred'].mean()
                 for df, _ in station_data.values()]) * 100
        if station_data else 0.0
    )

    print(f"\n{'─'*65}")
    print(f"  Loaded   : {len(station_data)} / {len(BANGLADESH_STATIONS)} stations")
    print(f"  Upstream : {len(upstream_data)} catchments")
    print(f"  Flood rate: {overall_flood:.1f}%  (target 12–18%)")

    if len(station_data) < len(BANGLADESH_STATIONS):
        still_missing = [
            f"{s['name']}_{s['district']}"
            for s in BANGLADESH_STATIONS
            if f"{s['name']}_{s['district']}" not in station_data
        ]
        print(f"\n  Still missing ({len(still_missing)}):")
        for m in still_missing:
            print(f"    - {m}")
        print(f"\n  Re-run this cell to fetch remaining stations.")
        print(f"  Cached stations load in milliseconds.")

    print(f"\n  {'Station':<36} {'Elev':>5}  {'Rows':>6}  {'Flood%':>8}")
    print(f"  {'─'*62}")
    for label, (df, info) in station_data.items():
        print(f"  {label:<36} "
              f"{info.get('elevation_m', 0):>4.0f}m  "
              f"{len(df):>6}  "
              f"{df['flood_occurred'].mean()*100:>7.1f}%")

    return station_data, upstream_data, station_metas


# ================================================================
# RUN
# ================================================================

station_data, upstream_data, all_stations = load_all_data()

#  BUILD FEATURE DATASET

def temporal_sample_weights(index):
    """
    Returns a numpy array of per-sample weights based on year.
    Pass this to XGBoost's sample_weight and LSTM's sample_weight.

    Parameters
    ----------
    index : pd.DatetimeIndex
        The index of X_train (or y_train).

    Returns
    -------
    np.ndarray of float, same length as index.
    """
    year = pd.Series(index.year, index=index)
    w    = pd.Series(1.0, index=index)

    w[year < 1990]                          = 0.55
    w[(year >= 1990) & (year < 2000)]       = 0.70
    w[(year >= 2000) & (year < 2010)]       = 0.85
    w[year >= 2010]                         = 1.00

    return w.values


def build_dataset(station_data, upstream_data):
    all_dfs = []
    for label, (df, info) in station_data.items():
        feat_df = compute_physics_features(
            df,
            elevation_m=info['elevation_m'],
            slope=info['slope'],
            river_name=info.get('name', ''),
        )
        # Add upstream lag features
        for up_name, up_df in upstream_data.items():
            short = up_name.split('_')[0][:5]
            up_rain = up_df['rainfall_mm'].reindex(feat_df.index, method='nearest')
            for lag in [2, 3, 4, 5, 7]:
                feat_df[f'up_{short}_lag{lag}d'] = up_rain.shift(lag)
            feat_df[f'up_{short}_7d_sum'] = up_rain.rolling(7).sum()
        all_dfs.append(feat_df)

    combined = pd.concat(all_dfs).sort_index().fillna(method='ffill').fillna(0)
    flood_rate = combined['flood_occurred'].mean() * 100
    print(f"Combined dataset: {combined.shape}  |  Flood rate: {flood_rate:.1f}%")
    return combined


combined_df = build_dataset(station_data, upstream_data)

EXCLUDE = {'flood_occurred', 'flood_severity', 'station', 'danger_thresh',
           'water_level_m', 'temp_max', 'temp_min'}
FEATURE_COLS = [c for c in combined_df.columns
                if c not in EXCLUDE
                and combined_df[c].dtype in [float, np.float64, np.float32,
                                              int, np.int64, np.int32]]
train = combined_df[combined_df.index <  VAL_START]
val   = combined_df[combined_df.index >= VAL_START]
X_train = train[FEATURE_COLS];  y_train = train['flood_occurred']
X_val   = val[FEATURE_COLS];    y_val   = val['flood_occurred']
flood_weight = float((y_train == 0).sum() / max((y_train == 1).sum(), 1))
print(f"Train: {len(X_train):,}  Val: {len(X_val):,}  Flood weight: {flood_weight:.1f}x")

# SECTION 8 — XGBoost (unchanged architecture, new features)
# ================================================================

print("\n" + "="*55)
print(" MODEL 1: XGBOOST")
print("="*55)

xgb_model = xgb.XGBClassifier(
    n_estimators=600, learning_rate=0.04, max_depth=6,
    subsample=0.80, colsample_bytree=0.80, min_child_weight=5,
    scale_pos_weight=flood_weight, eval_metric='auc',
    early_stopping_rounds=40, random_state=42, n_jobs=-1, verbosity=0,
)
# NEW — add sample_weight:
xgb_sw = temporal_sample_weights(X_train.index)
xgb_model.fit(
     X_train, y_train,
     sample_weight=xgb_sw,
     eval_set=[(X_val, y_val)],
     verbose=False,
 )

# Calculate xgb_probs for the validation set
xgb_probs = xgb_model.predict_proba(X_val)[:, 1]

feat_imp = pd.Series(xgb_model.feature_importances_,
                     index=FEATURE_COLS).sort_values(ascending=False)
print("\nTop 10 features:")
for f, s in feat_imp.head(10).items():
    print(f"  {f:<40} {s:.5f}")

import os, time, json, warnings
warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
import pandas as pd
import requests
from datetime import datetime, timedelta
from pathlib import Path

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import roc_auc_score, f1_score, classification_report

import xgboost as xgb
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

print(f"TensorFlow : {tf.__version__}")
print(f"XGBoost    : {xgb.__version__}")
print("Imports done.")

# SECTION 9 — LSTM  (unchanged architecture, new physics features)
# ================================================================

print("\n" + "="*55)
print(" MODEL 2: LSTM")
print("="*55)

scaler_lstm = MinMaxScaler()
X_tr_sc = scaler_lstm.fit_transform(X_train)
X_va_sc = scaler_lstm.transform(X_val)

def make_sequences(X, y, seq_len):
    Xs, ys = [], []
    for i in range(seq_len, len(X)):
        Xs.append(X[i - seq_len:i])
        ys.append(y[i])
    return np.array(Xs, dtype=np.float32), np.array(ys, dtype=np.float32)

X_tr_seq, y_tr_seq = make_sequences(X_tr_sc, y_train.values, SEQUENCE_LENGTH)
X_va_seq, y_va_seq = make_sequences(X_va_sc, y_val.values, SEQUENCE_LENGTH)

inp = keras.Input(shape=(SEQUENCE_LENGTH, X_tr_seq.shape[2]))
x = layers.LSTM(64, return_sequences=True)(inp)
x = layers.Dropout(0.40)(x)
x = layers.LSTM(32, return_sequences=True)(x)
x = layers.Dropout(0.30)(x)
x = layers.LSTM(16)(x)
x = layers.Dropout(0.25)(x)
x = layers.Dense(32, activation='relu')(x)
x = layers.BatchNormalization()(x)
out = layers.Dense(1, activation='sigmoid')(x)
lstm_model = keras.Model(inp, out)
lstm_model.compile(optimizer=keras.optimizers.Adam(1e-4),
                   loss='binary_crossentropy', metrics=['AUC'])

# Define the missing 'cbs' variable
cbs = [
    keras.callbacks.EarlyStopping(
        monitor='val_auc',
        patience=10,
        restore_best_weights=True,
        mode='max'
    ),
    keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=5,
        min_lr=1e-6
    )
]
# NEW — compute trimmed sample weights for LSTM, incorporating class weights:
base_seq_sw = temporal_sample_weights(X_train.index)[SEQUENCE_LENGTH:]
combined_seq_sw = np.array(base_seq_sw)
y_tr_seq_for_weights = y_train.values[SEQUENCE_LENGTH:]
combined_seq_sw[y_tr_seq_for_weights == 1] *= flood_weight

lstm_model.fit(
     X_tr_seq, y_tr_seq,
     sample_weight=combined_seq_sw,
     validation_data=(X_va_seq, y_va_seq),
     epochs=60,
     batch_size=64,
     # Removed class_weight argument as it conflicts with sample_weight
     callbacks=cbs,
     verbose=1,
 )
lstm_probs = lstm_model.predict(X_va_seq, verbose=0).flatten()
lstm_auc   = roc_auc_score(y_va_seq, lstm_probs)
lstm_f1    = f1_score(y_va_seq, (lstm_probs > 0.5).astype(int))
print(f"  AUC: {lstm_auc:.4f}   F1: {lstm_f1:.4f}")

#  VERIFICATION
# checking that both fixes are working or not
# ================================================================

def verify_fixes(combined_df, X_train):
    """
    Checks that the new features exist and sample weights
    are distributed correctly.
    """
    print("=" * 55)
    print(" VERIFICATION — climate fixes")
    print("=" * 55)

    # Check new features exist
    required = ['pct_rain_7d', 'pct_api', 'pct_water_level',
                'climate_shock_idx', 'days_from_monsoon_peak']
    missing  = [f for f in required if f not in combined_df.columns]
    if missing:
        print(f"  MISSING features: {missing}")
    else:
        print("  New climate-agnostic features: OK")
        print(f"    climate_shock_idx range: "
              f"{combined_df['climate_shock_idx'].min():.3f} – "
              f"{combined_df['climate_shock_idx'].max():.3f}")

    # Confirm hard seasonal flags are gone
    blocked = ['is_monsoon', 'is_premonsoon', 'is_postmonsoon']
    present = [f for f in blocked if f in combined_df.columns]
    if present:
        print(f"  WARNING: seasonal blocking flags still present: {present}")
    else:
        print("  Hard seasonal blocking flags: removed OK")

    # Check sample weight distribution
    sw = temporal_sample_weights(X_train.index)
    total = len(sw)
    for decade, lo, hi in [
        ("1979–1989", 1979, 1990),
        ("1990–1999", 1990, 2000),
        ("2000–2009", 2000, 2010),
        ("2010+",     2010, 2100),
    ]:
        mask = (X_train.index.year >= lo) & (X_train.index.year < hi)
        n    = mask.sum()
        if n > 0:
            w_mean = sw[mask].mean()
            print(f"  {decade}: {n:6,} rows  mean weight = {w_mean:.2f}")

    print("=" * 55)

#  MODEL 3 FIX — UNet Concatenate shape mismatch
# ================================================================
# SPATIAL DATASET GENERATOR
# ================================================================

def create_spatial_dataset(n=1200, rows=GRID_ROWS, cols=GRID_COLS,
                            ch=N_CHANNELS):
    """
    Generates synthetic Bangladesh spatial data for UNet training.

    Grid size is now 24×24 — both dimensions divisible by 4,
    so MaxPooling2D(2) twice and Conv2DTranspose(2) twice
    produce exact round-trip dimensions with no rounding.

    Channel layout (7 channels):
      0  Daily rainfall (mm)
      1  Elevation (m) from SRTM
      2  Terrain slope (derived from elevation gradient)
      3  Soil moisture (0–1)
      4  Distance to nearest river (0–1)
      5  Upstream India/Nepal rainfall — lagged 3 days
      6  Flood Susceptibility Index = (1/elev) × (1/slope)
    """
    np.random.seed(42)
    Xs, ys = [], []

    for _ in range(n):
        img = np.zeros((rows, cols, ch), dtype=np.float32)

        # Ch 0 — Rainfall
        rain          = np.random.exponential(25, (rows, cols)).astype(np.float32)
        rain[:8, 14:] *= 2.8    # Sylhet / Sunamganj: very high
        rain[8:16, :8]*= 1.4    # Brahmaputra corridor: elevated
        img[:, :, 0]   = np.clip(rain, 0, 220)

        # Ch 1 — Elevation
        elev              = np.zeros((rows, cols), dtype=np.float32)
        elev[16:, 16:]    = np.random.uniform(80, 900, (8, 8))   # Chittagong Hills
        elev[:6,  18:]    = np.random.uniform(30, 250, (6, 6))   # Sylhet hills
        elev[6:16, :16]   = np.random.uniform(0,   12, (10, 16)) # Main floodplain
        img[:, :, 1]      = elev

        # Ch 2 — Slope (gradient of elevation)
        gy, gx         = np.gradient(elev)
        slope_map      = np.sqrt(gx**2 + gy**2)
        img[:, :, 2]   = np.clip(slope_map, 0, 30)

        # Ch 3 — Soil moisture
        sm             = np.random.uniform(0.3, 0.85, (rows, cols)).astype(np.float32)
        sm[6:16, :16]  = np.random.uniform(0.65, 0.97, (10, 16))
        img[:, :, 3]   = sm

        # Ch 4 — Distance to nearest river
        rdist = np.ones((rows, cols), dtype=np.float32)
        for rc in [4, 7, 11, 16]:
            for c in range(cols):
                rdist[:, c] = np.minimum(rdist[:, c], abs(c - rc) / cols)
        img[:, :, 4] = rdist

        # Ch 5 — Upstream rainfall (lagged 3 days)
        up         = np.random.exponential(18, (rows, cols)).astype(np.float32)
        up[:6, :]  *= 2.1
        img[:, :, 5] = up

        # Ch 6 — Flood Susceptibility Index (physics formula)
        low_elev     = 1.0 / (1.0 + elev / 15.0)
        flat         = 1.0 / (1.0 + slope_map * 5000)
        img[:, :, 6] = (low_elev * flat).astype(np.float32)

        # Label — flood probability from physics (no historical labels)
        flood_prob = (
            low_elev          * 0.30 +
            (rain / 220)      * 0.25 +
            sm                * 0.20 +
            (1 - rdist)       * 0.15 +
            flat              * 0.10
        )
        flood_prob += np.random.normal(0, 0.04, (rows, cols))
        ys.append((flood_prob > 0.52).astype(np.float32))
        Xs.append(img)

    return np.array(Xs), np.array(ys)[..., np.newaxis]


X_sp, y_sp   = create_spatial_dataset(n=1200)
split        = int(0.8 * len(X_sp))
X_sp_tr, X_sp_va = X_sp[:split], X_sp[split:]
y_sp_tr, y_sp_va = y_sp[:split], y_sp[split:]

sp_mean = X_sp_tr.mean(axis=(0, 1, 2), keepdims=True)
sp_std  = X_sp_tr.std( axis=(0, 1, 2), keepdims=True) + 1e-8
X_sp_tr = (X_sp_tr - sp_mean) / sp_std
X_sp_va = (X_sp_va - sp_mean) / sp_std

print(f"Spatial train: {X_sp_tr.shape}   val: {X_sp_va.shape}")
print(f"Label  train: {y_sp_tr.shape}   val: {y_sp_va.shape}")


# ================================================================
# UNET  (with crop_to_match safety)
# ================================================================

def crop_to_match(tensor, target):
    """
    Crops `tensor` so its spatial dimensions match `target`.

    Why this exists:
      After two rounds of MaxPooling2D(2) + Conv2DTranspose(2),
      integer rounding means the upsampled shape can be off by
      ±1 pixel vs the skip connection it needs to concatenate with.
      This function trims the extra row or column so Concatenate
      never sees a mismatch — regardless of grid dimensions.

    With GRID_ROWS=24 and GRID_COLS=24 this function does nothing
    (both tensors are already the same size). It is kept as a
    safety net in case the grid dimensions are changed later.
    """
    ts = tf.shape(tensor)
    tg = tf.shape(target)
    # Crop height if needed
    h  = tf.minimum(ts[1], tg[1])
    # Crop width if needed
    w  = tf.minimum(ts[2], tg[2])
    return tensor[:, :h, :w, :]


def build_unet(shape=(GRID_ROWS, GRID_COLS, N_CHANNELS)):
    """
    U-Net encoder–decoder with skip connections.

    Shape check before building:
      Both spatial dimensions must be divisible by 4 for clean
      round-trip pooling. This is now guaranteed by GRID_COLS=24.

    Architecture:
      Encoder block 1: Conv→BN→Conv → c1 (skip)  → Pool → p1
      Encoder block 2: Conv→BN→Conv → c2 (skip)  → Pool → p2
      Bottleneck     : Conv→BN→Conv → bn
      Decoder block 1: Upsample → crop_to_match(c2) → Concat → Conv→Conv
      Decoder block 2: Upsample → crop_to_match(c1) → Concat → Conv→Conv
      Output         : Conv2D(1, sigmoid) → flood probability per pixel
    """
    rows, cols, _ = shape
    assert rows % 4 == 0, f"GRID_ROWS ({rows}) must be divisible by 4"
    assert cols % 4 == 0, f"GRID_COLS ({cols}) must be divisible by 4"

    inp = keras.Input(shape=shape)

    # ── Encoder ──
    c1 = layers.Conv2D(32, 3, activation='relu', padding='same')(inp)
    c1 = layers.BatchNormalization()(c1)
    c1 = layers.Conv2D(32, 3, activation='relu', padding='same')(c1)
    p1 = layers.MaxPooling2D(2)(c1)
    p1 = layers.Dropout(0.10)(p1)

    c2 = layers.Conv2D(64, 3, activation='relu', padding='same')(p1)
    c2 = layers.BatchNormalization()(c2)
    c2 = layers.Conv2D(64, 3, activation='relu', padding='same')(c2)
    p2 = layers.MaxPooling2D(2)(c2)
    p2 = layers.Dropout(0.10)(p2)

    # ── Bottleneck ──
    bn = layers.Conv2D(128, 3, activation='relu', padding='same')(p2)
    bn = layers.BatchNormalization()(bn)
    bn = layers.Conv2D(128, 3, activation='relu', padding='same')(bn)

    # ── Decoder ──
    u4 = layers.Conv2DTranspose(64, 2, strides=2, padding='same')(bn)
    # crop_to_match ensures shapes agree even if rounding produces ±1 diff
    u4 = layers.Lambda(lambda t: crop_to_match(t[0], t[1]))([u4, c2])
    u4 = layers.Concatenate()([u4, c2])
    c4 = layers.Conv2D(64, 3, activation='relu', padding='same')(u4)
    c4 = layers.Conv2D(64, 3, activation='relu', padding='same')(c4)

    u5 = layers.Conv2DTranspose(32, 2, strides=2, padding='same')(c4)
    u5 = layers.Lambda(lambda t: crop_to_match(t[0], t[1]))([u5, c1])
    u5 = layers.Concatenate()([u5, c1])
    c5 = layers.Conv2D(32, 3, activation='relu', padding='same')(u5)
    c5 = layers.Conv2D(32, 3, activation='relu', padding='same')(c5)

    # ── Output — one flood probability per pixel ──
    out = layers.Conv2D(1, 1, activation='sigmoid')(c5)

    m = keras.Model(inp, out)
    m.compile(
        optimizer=keras.optimizers.Adam(1e-3),
        loss='binary_crossentropy',
        metrics=['accuracy', tf.keras.metrics.AUC(name='auc')],
    )
    return m


unet_model = build_unet()
unet_model.summary()

# ── Training ──
unet_hist = unet_model.fit(
    X_sp_tr, y_sp_tr,
    validation_data=(X_sp_va, y_sp_va),
    epochs=40,
    batch_size=16,
    callbacks=[
        EarlyStopping(monitor='val_auc', patience=10,
                      mode='max', restore_best_weights=True)
    ],
    verbose=1,
)

# ── Quick sanity check ──
sample_preds = unet_model.predict(X_sp_va[:4], verbose=0)
print(f"\nUNet output shape : {sample_preds.shape}")
print(f"Mean flood prob   : {sample_preds.mean():.3f}")
print(f"Min / Max         : {sample_preds.min():.3f} / {sample_preds.max():.3f}")
print("UNet training complete.")

# ================================================================
# REMINDER

# The global variable is overwritten here at the top of this
# cell so the rest of the notebook uses 24 automatically.
# ================================================================

# Call after training:
verify_fixes(combined_df, X_train)

def predict_any_location(lat, lon, location_name=None, days_forecast=3):
    """
    Predicts flood risk for ANY latitude/longitude in Bangladesh.
    Works for areas with no flood history by using physics features.

    Steps:
      1. Fetch real SRTM elevation for the point (OpenTopoData)
      2. Estimate slope from nearby elevation points
      3. Fetch 50 days of weather history (NASA POWER)
      4. Fetch 3-7 day forecast (Open-Meteo Forecast)
      5. Build physics features (FSI, saturation, anomaly)
      6. Run XGBoost + LSTM + UNet
      7. Compute DYNAMIC risk score from current conditions
      8. Return result with risk level
    """
    if location_name is None:
        location_name = f"({lat:.3f}, {lon:.3f})"

    # Determine the correct name/label for caching and API calls
    actual_name = location_name
    matched_station_info = None
    # Iterate through all_stations to find a match and use its cached label
    # all_stations is a global variable populated by load_all_data()
    for st_info in all_stations:
        # Using a small tolerance for floating point comparisons
        if abs(st_info['lat'] - lat) < 0.001 and abs(st_info['lon'] - lon) < 0.001:
            actual_name = st_info['label']
            matched_station_info = st_info
            break

    print(f"\n[ REAL-TIME ] Predicting for: {location_name} (Internal label: {actual_name})")

    # Step 1 — get elevation for this exact coordinate
    try:
        r = requests.get(TOPO_URL, params={'locations': f'{lat},{lon}'}, timeout=15)
        elevation_m = r.json()['results'][0].get('elevation', 10.0)
    except:
        elevation_m = 10.0
        print("  Could not fetch elevation — using 10m default")

    # Estimate slope from 4 nearby points
    offsets = [(0.05, 0), (-0.05, 0), (0, 0.05), (0, -0.05)]
    try:
        locs = "|".join(f"{lat+dy},{lon+dx}" for dy, dx in offsets)
        r    = requests.get(TOPO_URL, params={'locations': locs}, timeout=15)
        nn_elevs = [x.get('elevation', elevation_m)
                    for x in r.json().get('results', [])]
        diffs    = [abs(e - elevation_m) for e in nn_elevs]
        slope    = float(np.mean(diffs)) / (0.05 * 111_000)
    except:
        slope = 0.001

    print(f"  Elevation: {elevation_m:.1f}m   Slope: {slope:.6f}")

    # Step 2 — fetch weather history using NASA POWER API
    # Ensure dates are in the past for archive API
    # Using VAL_END as the historical end date to be consistent with training data
    # and avoid issues with system date if it reports a future year.
    hist_en = VAL_END # This is '2023-12-31'
    hist_st = (pd.to_datetime(VAL_END) - timedelta(days=55)).strftime('%Y-%m-%d')

    # Pass the determined actual_name to fetch_nasa_power
    hist, _ = fetch_nasa_power(lat, lon, hist_st, hist_en, name=actual_name, elevation_m=elevation_m)
    if hist is None:
        print("  NASA POWER API unavailable for historical data. Cannot predict.")
        return None

    hist = simulate_water_level(hist, elevation_m)

    # Step 3 — physics features
    # If matched_station_info was found, use its pre-computed elevation and slope
    if matched_station_info:
        feat_df = compute_physics_features(hist,
                                           elevation_m=matched_station_info['elevation_m'],
                                           slope=matched_station_info['slope'])
    else:
        feat_df = compute_physics_features(hist, elevation_m, slope)

    for up_name, up_df in upstream_data.items():
        short = up_name.split('_')[0][:5]
        up_rain = up_df['rainfall_mm'].reindex(feat_df.index, method='nearest')
        for lag in [2, 3, 4, 5, 7]:
            feat_df[f'up_{short}_lag{lag}d'] = up_rain.shift(lag)
        feat_df[f'up_{short}_7d_sum'] = up_rain.rolling(7).sum()
    feat_df = feat_df.fillna(method='ffill').fillna(0)

    if len(feat_df) < SEQUENCE_LENGTH + 2:
        print(f"  Not enough history ({len(feat_df)} rows).")
        return None

    # Step 4 — XGBoost prediction
    today_row = feat_df[FEATURE_COLS].tail(1).reindex(
        columns=FEATURE_COLS, fill_value=0)
    xgb_p = float(xgb_model.predict_proba(today_row)[0, 1])

    # Step 5 — LSTM prediction
    seq   = feat_df[FEATURE_COLS].tail(SEQUENCE_LENGTH).values
    seq_s = scaler_lstm.transform(seq)[np.newaxis].astype(np.float32)
    lstm_p = float(lstm_model.predict(seq_s, verbose=0)[0, 0])

    # Step 6 — UNet spatial estimate
    sp_demo = create_spatial_dataset(n=1)[0][:1]
    sp_norm = (sp_demo - sp_mean) / sp_std
    flood_map = unet_model.predict(sp_norm, verbose=0)[0, :, :, 0]
    unet_p    = float(flood_map.mean())

    # Step 7 — DYNAMIC risk score (no static label)
    dynamic_score = compute_dynamic_risk_score(feat_df.tail(1), feat_df)

    # Hybrid model probability
    model_p = 0.40 * xgb_p + 0.40 * lstm_p + 0.20 * unet_p

    # Final score blends model output with dynamic physics score
    final_score = 0.65 * model_p + 0.35 * dynamic_score

    level, colour, _ = risk_level_from_score(final_score)
    rst = "\033[0m"

    # Step 8 — Forecast
    fcast = fetch_forecast(lat, lon, location_name, days=days_forecast)

    # Physics explanation for why this location is at risk
    fsi = float(feat_df['flood_susceptibility_idx'].iloc[-1])
    sat = float(feat_df['saturation_idx'].iloc[-1])
    anom = float(feat_df['rain_anomaly'].iloc[-1])

    print("\n" + "=" * 55)
    print(f"  FLOOD RISK — {location_name.upper()}")
    print("=" * 55)
    print(f"  RISK LEVEL     : {colour}[ {level} ]{rst}")
    print(f"  Final score    : {final_score:.1%}")
    print(f"  ├─ ML model    : {model_p:.1%}  (XGBoost + LSTM + UNet)")
    print(f"  └─ Physics     : {dynamic_score:.1%}  (live conditions vs seasonal norm)")
    print(f"\n  Physics breakdown:")
    print(f"  ├─ Elevation        : {elevation_m:.1f} m")
    print(f"  ├─ Flood susc. idx  : {fsi:.3f}  (0=safe, 1=very vulnerable)")
    print(f"  ├─ Soil saturation  : {sat:.3f}  (0=dry, 1=waterlogged)")
    print(f"  └─ Rainfall anomaly : {anom:.2f}x  (vs seasonal normal)")

    if fcast is not None:
        print(f"\n  Forecast (next {days_forecast} days):")
        for dt, row in fcast.head(days_forecast).iterrows():
            bar = '#' * max(0, int(row['rainfall_mm'] / 5))
            print(f"    {dt.strftime('%b %d')} : {row['rainfall_mm']:5.1f} mm  {bar}")

    return {
        'location': location_name, 'lat': lat, 'lon': lon,
        'elevation_m': elevation_m, 'slope': slope,
        'flood_susceptibility_idx': fsi,
        'risk_level': level, 'final_score': round(final_score, 4),
        'model_prob': round(model_p, 4),
        'dynamic_risk': round(dynamic_score, 4),
        'xgb_prob': round(xgb_p, 4), 'lstm_prob': round(lstm_p, 4),
        'unet_prob': round(unet_p, 4),
        'flood_map': flood_map, 'forecast': fcast,
    }

# SECTION 12 — VISUALISATION DASHBOARD
# ================================================================

def plot_dashboard(results_list):
    n_plots = min(len(results_list), 3)
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle(
        'Bangladesh Flood Prediction v2 — Physics-Based, Dynamic Risk',
        fontsize=14, fontweight='bold')

    # Model performance
    ax = axes[0, 0]
    models_lbl = ['XGBoost', 'LSTM', 'Hybrid']
    n_al  = min(len(xgb_probs), len(lstm_probs))
    xgb_a = xgb_probs[-n_al:]
    lst_a = lstm_probs[-n_al:]
    y_a   = y_val.values[-n_al:]
    sp    = float(unet_model.predict(
        (create_spatial_dataset(n=1)[0][:1] - sp_mean) / sp_std,
        verbose=0).mean())
    hybrid = 0.4 * xgb_a + 0.4 * lst_a + 0.2 * sp
    aucs   = [roc_auc_score(y_a, xgb_a),
              roc_auc_score(y_va_seq, lstm_probs),
              roc_auc_score(y_a, hybrid)]
    ax.bar(models_lbl, aucs, color=['#1D9E75','#534AB7','#D85A30'], alpha=0.85)
    ax.set(title='AUC-ROC by model', ylabel='AUC-ROC', ylim=(0, 1.1))
    for i, v in enumerate(aucs):
        ax.text(i, v + 0.01, f'{v:.3f}', ha='center', fontsize=11)
    ax.grid(True, alpha=0.2, axis='y')

    # Physics feature importance (top 12)
    ax = axes[0, 1]
    top = feat_imp.head(12)
    colours = ['#1D9E75' if any(k in f for k in
               ['suscept','saturation','anomaly','api','fsi','elev','slope'])
               else '#534AB7' for f in top.index]
    ax.barh(range(len(top)), top.values[::-1], color=colours[::-1])
    ax.set_yticks(range(len(top)))
    ax.set_yticklabels([f.replace('_',' ')[:32] for f in top.index[::-1]], fontsize=9)
    ax.set(title='Top 12 features — physics features highlighted', xlabel='Importance')
    handles = [
        mpatches.Patch(color='#1D9E75', label='Physics features (new)'),
        mpatches.Patch(color='#534AB7', label='Other features'),
    ]
    ax.legend(handles=handles, fontsize=9)

    # Dynamic risk scores for all stations in result_list
    ax = axes[1, 0]
    if results_list:
        locs  = [r['location'][:18] for r in results_list]
        scores= [r['final_score']   for r in results_list]
        dyn   = [r['dynamic_risk']  for r in results_list]
        x     = np.arange(len(locs))
        ax.bar(x - 0.2, scores, 0.38, label='Final (hybrid)', color='#1D9E75', alpha=0.85)
        ax.bar(x + 0.2, dyn,    0.38, label='Dynamic risk',   color='#D85A30', alpha=0.85)
        ax.set_xticks(x); ax.set_xticklabels(locs, fontsize=9, rotation=20)
        ax.set(title='Dynamic risk vs hybrid score per location',
               ylabel='Score (0-1)', ylim=(0, 1.1))
        ax.axhline(0.45, color='orange', ls='--', lw=1, label='Warning threshold')
        ax.axhline(0.68, color='red',    ls='--', lw=1, label='Danger threshold')
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.2, axis='y')
    else:
        ax.text(0.5, 0.5, 'No prediction results', ha='center', va='center',
                transform=ax.transAxes)

    # UNet flood map
    ax = axes[1, 1]
    if results_list:
        fm = results_list[0]['flood_map']
    else:
        sp_demo = create_spatial_dataset(n=1)[0][:1]
        fm = unet_model.predict((sp_demo - sp_mean) / sp_std, verbose=0)[0, :, :, 0]
    im = ax.imshow(fm, cmap='RdYlGn_r', vmin=0, vmax=1, aspect='auto')
    plt.colorbar(im, ax=ax, label='Flood probability')
    ax.set(title=f'UNet spatial map — {results_list[0]["location"] if results_list else "Bangladesh"}',
           xlabel='West → East', ylabel='North → South')

    plt.tight_layout()
    out = 'flood_v2_dashboard.png'
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Dashboard saved: {out}")

# SECTION 13 — RUN PREDICTIONS
# ================================================================

print("\n" + "="*55)
print(" REAL-TIME PREDICTIONS")
print("="*55)

# Named districts — same as before
named_locations = [
    ('Kurigram',  25.807, 89.636),
    ('Sirajganj', 24.451, 89.701),
]

# ANY arbitrary coordinate — no training data needed, uses physics
arbitrary_locs = [
    ('Rural Gopalganj', 23.003, 89.826),   # never in hardcoded list
    ('Cox_s Bazar coast', 21.448, 92.018), # coastal, climate-risk area
]

results = []
for name, lat, lon in named_locations + arbitrary_locs:
    r = predict_any_location(lat, lon, name, days_forecast=3)
    if r:
        results.append(r)

print("\nGenerating dashboard ...")
plot_dashboard(results)

